grounding_dino:
  config_file: ""
  checkpoint: "models/g-sam/groundingdino_swint_ogc.pth"
  box_threshold: 0.35
  text_threshold: 0.25
  device: "cuda"

sam:
  model_type: "vit_b"
  checkpoint: "models/g-sam/sam_vit_b_01ec64.pth"
  device: "cuda"
